- hosts: localhost
  become: true
  vars:
    home: /home/vagrant/
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/cron.yml
    - include: tasks/rc_files.yml
