- name: deploy .vimrc
  copy:
    src: files/vimrc
    dest: /home/vagrant/.vimrc
    owner: ja
    group: ja
    mode: 0664 

- name: deploy ansible.cfg
  copy:
    src: files/ansible.cfg
    dest: /home/vagrant/ansible.cfg
    owner: ja
    group: ja

- name: deploy .gitconfig file
  copy:
    src: files/gitconfig
    dest: /home/vagrant/.gitconfig
    owner: ja
    group: ja

