- name: deploy .vimrc
  copy:
    src: files/vimrc
    dest: "{{ home }}.vimrc"
    owner: vagrant
    group: vagrant
    mode: 0664 

- name: deploy ansible.cfg
  copy:
    src: files/ansible.cfg
    dest: "{{ home }}ansible.cfg"
    owner: vagrant
    group: vagrant

- name: deploy .gitconfig file
  copy:
    src: files/gitconfig
    dest: "{{ home }}.gitconfig"
    owner: vagrant
    group: vagrant

