- name: deploy .vimrc
  copy:
    src: files/vimrc
    dest: /home/ja/.vimrc
    owner: ja
    group: ja
    mode: 0664 

- name: deploy ansible.cfg
  copy:
    src: files/ansible.cfg
    dest: /home/ja/ansible.cfg
    owner: ja
    group: ja

- name: deploy .gitconfig file
  copy:
    src: files/gitconfig
    dest: /home/ja/ansible.cfg
    owner: ja
    group: ja

